name: Build Project

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - name: build debug
      run: |
        chmod +x ./gradlew
        ./gradlew :module:assembleDebug
    - name: upload build
      uses: actions/upload-artifact@v4
      with: 
        name: module
        path: module/
        
  
